const fs = require("fs");
const existing = fs.readFileSync("src/utils/pdfGenerator.js","utf8");
const out = [existing];
const w = (s) => out.push(s);

// ── renderRichLine: render satu baris dengan inline segments ──
w("// Render satu baris teks dengan format inline (bold/italic/underline/link/tab)");
w("// Mengembalikan lebar teks yang dirender (untuk keperluan tabel)");
w("function renderRichLine(doc, segs, x, y, maxW, align, isArabicLine){");
w("  if(isArabicLine){");
w("    const txt=segs.map(s=>s.text).join('');");
w("    const shaped=reshapeArabic(txt);");
w("    doc.font(F_ARAB).fontSize(FS_ARAB).fillColor('#000000');");
w("    doc.text(shaped,x,y,{width:maxW,align:'center',lineGap:LINE_GAP});");
w("    return;");
w("  }");
w("  // Untuk align non-left, render sebagai satu blok dulu (PDFKit handle align)");
w("  // Tapi untuk mixed format, kita perlu render segment per segment");
w("  // Pendekatan: jika semua segment sama format → pakai doc.text biasa");
w("  // Jika mixed → render dengan continued:true per segment");
w("  const allSame = segs.every(s=>s.bold===segs[0].bold&&s.italic===segs[0].italic&&s.underline===segs[0].underline&&!s.link&&!s.isTab);");
w("  if(allSame&&segs.length>0){");
w("    const s=segs[0];");
w("    doc.font(pickFont(s.bold,s.italic)).fontSize(FS_ISI).fillColor('#000000');");
w("    const txt=segs.map(g=>g.text).join('');");
w("    if(s.underline)doc.text(txt,x,y,{width:maxW,align,lineGap:LINE_GAP,underline:true});");
w("    else doc.text(txt,x,y,{width:maxW,align,lineGap:LINE_GAP});");
w("    return;");
w("  }");
w("  // Mixed format: render segment per segment dengan continued");
w("  // Untuk alignment non-left, hitung total lebar dulu lalu offset x");
w("  let startX=x;");
w("  if(align==='center'||align==='right'){");
w("    let totalW=0;");
w("    for(const s of segs){");
w("      if(s.isTab){totalW+=TAB_W;continue;}");
w("      doc.font(pickFont(s.bold,s.italic)).fontSize(FS_ISI);");
w("      totalW+=doc.widthOfString(s.text);");
w("    }");
w("    if(align==='center')startX=x+(maxW-totalW)/2;");
w("    else startX=x+maxW-totalW;");
w("    startX=Math.max(x,startX);");
w("  }");
w("  let cx=startX;");
w("  for(let si=0;si<segs.length;si++){");
w("    const s=segs[si];");
w("    const isLast=si===segs.length-1;");
w("    if(s.isTab){cx+=TAB_W;continue;}");
w("    if(!s.text)continue;");
w("    const font=pickFont(s.bold,s.italic);");
w("    doc.font(font).fontSize(FS_ISI);");
w("    const sw=doc.widthOfString(s.text);");
w("    const opts={lineBreak:false,lineGap:LINE_GAP};");
w("    if(s.underline||s.link)opts.underline=true;");
w("    if(s.link)doc.fillColor(LINK_COLOR);");
w("    else doc.fillColor('#000000');");
w("    doc.text(s.text,cx,y,opts);");
w("    if(s.link){");
w("      try{doc.link(cx,y,sw,FS_ISI+2,s.link);}catch(_){}");
w("      doc.fillColor('#000000');");
w("    }");
w("    cx+=sw;");
w("  }");
w("  // Advance cursor Y");
w("  doc.text('',x,y+FS_ISI+LINE_GAP,{lineBreak:false});");
w("}");
w("");

fs.writeFileSync("src/utils/pdfGenerator.js", out.join("\n"), "utf8");
console.log("block3 ok");
